### ISSUE TITLE
Other output formats

### ISSUE THREAD

**Issue by LecrisUT** [threeal/gcovr-action#151]
One deal-breaker for using this action is that it does not support outputting to other formats. Could either add input options for this, or support passing arbitrary `args`

**Comment by threeal** [comment]
What kind of output format that you want to use?

**Comment by LecrisUT** [comment]
Xml so that I can upload to codecov instead

**Comment by threeal** [comment]
We'll implement an `xml-out` option in #152. Expect it to be completed in several hours.

**Comment by threeal** [comment]
It's merged in #153, @LecrisUT. However, I am currently still working on a major refactoring of this action, so it will take more time before I can cut a new release. Although temporarily, you can use this feature by using `threeal/gcovr-action@xml-out`.

Let me know if you need any help.

**Comment by LecrisUT** [comment]
No worries, thanks for the quick update

**Comment by threeal** [comment]
@LecrisUT, I just wanted to let you know that you can use [v1.1.0](https://github.com/threeal/gcovr-action/releases/tag/v1.1.0) instead, as the `xml-out` tag will be deprecated soon.

**Comment by LecrisUT** [comment]
Awesome :)
