### ISSUE TITLE
convention: Moving `v1` tag

### ISSUE THREAD

**Issue by LecrisUT** [threeal/gcovr-action#155]
A common convention is to have a `vX` tag that is constantly updated after each minor/patch release. When I looked initially there was no action to do it automatically, but there was an action to parse tag release.

**Comment by threeal** [comment]
We don't need an action to do it automatically; we can just update the tags manually. It's not hard work, I just pushed the `v1` tag, although it still points to the [`v1.0.0`](https://github.com/threeal/gcovr-action/releases/tag/v1.0.0) release.
